export type Lang = "en" | "ka";

export const translations = {
  en: {
    nav: { demo: "Demo", whyClozes: "Why Clozes", howItWorks: "How It Works", forBrands: "For Brands", pricing: "Pricing", joinEarlyAccess: "Join Early Access" },
    hero: { badge: "Now Onboarding Brand Partners", title1: "Experience Clothes", title2: "Before You", title3: "Wear Them.", subtitle: "AI-powered fit intelligence that predicts comfort, sizing, and outfit compatibility before your customers buy — reducing returns and increasing trust.", tryDemo: "Try the Demo", joinEarlyAccess: "Join Early Access", fewerReturns: "Fewer Returns", fitAccuracy: "Fit Accuracy", analysisTime: "Analysis Time" },
    problem: { badge: "The Problem", title: "The Hidden Cost of Poor Fit", stat1: { value: "70%", label: "of fashion returns", sub: "due to poor fit" }, stat2: { value: "$218B", label: "lost annually", sub: "in return costs" }, stat3: { value: "64%", label: "abandon purchase", sub: "due to sizing uncertainty" } },
    howItWorks: { badge: "How It Works", title1: "Intelligence", title2: "In Motion.", subtitle: "Three simple steps from measurement to confident purchase.", step1: { title: "Input Measurements", desc: "Enter your body measurements or select your garment type. Our system builds a precise fit profile tailored to your dimensions." }, step2: { title: "Neural Analysis", desc: "The Clozes Engine maps the garment's technical specs against your unique body geometry, analyzing fit across dozens of data points." }, step3: { title: "Confident Purchase", desc: "Receive your recommended size with a detailed breakdown of comfort, mobility, and fit — before you spend a penny." } },
    outfit: { badge: "Outfit Intelligence", title1: "We Go Beyond Fit.", title2: "We Build Better Outfits", subtitle: "Clozes does not just find your size — it curates complete looks that work together." },
    b2b: { badge: "Clozes Platform", title: "Power Your Store With Fit Intelligence", subtitle: "One line of code. Instant size recommendations. Fewer returns.", feature1: { title: "Drop-in SDK", desc: "Add a Find My Fit button to your product pages in less than 10 lines of code. Fully white-labeled." }, feature2: { title: "Universal Profiles", desc: "When a shopper visits any Clozes-powered store, their fit profile travels with them. Zero friction." }, feature3: { title: "Proven ROI", desc: "Our partners see an average 38% decrease in size-related returns within the first quarter." }, demoTitle: "See exactly what your customers experience.", demoSubtitle: "This is the widget your shoppers see when they click Find My Fit on your product pages. Try it yourself.", demoPoints: ["Works on any website or platform", "Supports 10+ garment types", "Available in Mens and Womens sizing", "Powered by real size chart data"], launchDemo: "Launch Live Demo", findMyFit: "Find My Fit", formTitle: "Request API Integration", formSubtitle: "Tell us about your store and we will reach out to get you set up.", name: "Your Name", email: "Work Email", company: "Company / Brand Name", message: "Tell us about your store", messagePlaceholder: "Monthly orders, platform (Shopify, WooCommerce, custom), main challenges with returns...", submit: "Submit Integration Request", success: "Request Received!", successMsg: "We will be in touch within 1 business day to discuss your integration." },
    pricing: { badge: "Pricing", title: "Simple, Transparent Pricing", subtitle: "Start reducing returns today. No setup fees, no contracts.", monthly: "/ month", starter: { name: "Starter", price: "$299", desc: "Perfect for growing brands", features: ["Up to 1,000 fit analyses/month", "Basic analytics dashboard", "Email support", "Standard size charts", "Widget customization"] }, growth: { name: "Growth", price: "$799", desc: "For established brands", features: ["Up to 10,000 fit analyses/month", "Advanced analytics & trends", "Priority support", "Custom size charts", "Widget customization", "API access"] }, enterprise: { name: "Enterprise", price: "Custom", desc: "For large retailers", features: ["Unlimited fit analyses", "Dedicated account manager", "Custom integrations", "SLA guarantee", "White-label option"] }, getStarted: "Get Started", contactUs: "Contact Us" },
    waitlist: { badge: "Early Access", title: "Join the Future of Fashion.", subtitle: "Early access is limited. Secure your spot on the waitlist.", name: "Full Name", email: "Email Address", join: "Join Waitlist", joining: "Joining...", success: "You are on the list.", successMsg: "We will notify you when your access is ready." },
    footer: { tagline: "AI-powered fit intelligence for clothing brands. Reduce returns, increase confidence, grow revenue.", product: "Product", company: "Company", sizeFinder: "Size Finder", howItWorks: "How It Works", roadmap: "Roadmap", pricing: "Pricing", forBrands: "For Brands", earlyAccess: "Early Access", contact: "Contact", privacy: "Privacy Policy", copyright: "Clozes. All rights reserved." },
  },
  ka: {
    nav: { demo: "დემო", whyClozes: "რატომ Clozes", howItWorks: "როგორ მუშაობს", forBrands: "ბრენდებისთვის", pricing: "ფასები", joinEarlyAccess: "ადრეული წვდომა" },
    hero: { badge: "ახლა ვიწვევთ ბრენდ პარტნიორებს", title1: "გამოცადე ტანსაცმელი", title2: "სანამ", title3: "ჩაიცვამ.", subtitle: "ხელოვნური ინტელექტით მართული ზომების სისტემა, რომელიც ყიდვამდე წინასწარ განსაზღვრავს კომფორტს, ზომასა და თავსებადობას — ამცირებს დაბრუნებებს და ზრდის ნდობას.", tryDemo: "სცადე დემო", joinEarlyAccess: "შეუერთდი სიას", fewerReturns: "ნაკლები დაბრუნება", fitAccuracy: "ზომის სიზუსტე", analysisTime: "ანალიზის დრო" },
    problem: { badge: "პრობლემა", title: "ცუდი ზომის ფარული ფასი", stat1: { value: "70%", label: "მოდის დაბრუნებების", sub: "ცუდი ზომის გამო" }, stat2: { value: "$218 მლრდ", label: "იკარგება წელიწადში", sub: "დაბრუნების ხარჯებში" }, stat3: { value: "64%", label: "ტოვებს ყიდვას", sub: "ზომის გაურკვევლობის გამო" } },
    howItWorks: { badge: "როგორ მუშაობს", title1: "ინტელექტი", title2: "მოქმედებაში.", subtitle: "სამი მარტივი ნაბიჯი საზომიდან დარწმუნებულ ყიდვამდე.", step1: { title: "შეიყვანე საზომები", desc: "შეიყვანე სხეულის საზომები ან აირჩიე ტანსაცმლის სახეობა. ჩვენი სისტემა ქმნის ზუსტ ზომის პროფილს." }, step2: { title: "ნეირონული ანალიზი", desc: "Clozes-ის ძრავა ადარებს ტანსაცმლის მახასიათებლებს შენი სხეულის გეომეტრიასთან." }, step3: { title: "დარწმუნებული ყიდვა", desc: "მიიღე რეკომენდებული ზომა კომფორტის, მობილობისა და ზომის დეტალური ანალიზით." } },
    outfit: { badge: "კომბინაციების ინტელექტი", title1: "ჩვენ ზომაზე მეტს ვაკეთებთ.", title2: "ჩვენ ვქმნით უკეთეს კომბინაციებს", subtitle: "Clozes არა მხოლოდ პოულობს შენს ზომას — ის ქმნის სრულ სახეს, რომელიც ერთად მუშაობს." },
    b2b: { badge: "Clozes პლატფორმა", title: "გააძლიერე შენი მაღაზია ზომების ინტელექტით", subtitle: "ერთი სტრიქონი კოდი. მყისიერი ზომის რეკომენდაციები. ნაკლები დაბრუნება.", feature1: { title: "მარტივი SDK", desc: "დაამატე ღილაკი პროდუქტის გვერდებზე 10 სტრიქონზე ნაკლები კოდით." }, feature2: { title: "უნივერსალური პროფილები", desc: "მომხმარებლის ზომის პროფილი თან სდევს ნებისმიერ Clozes-ით მომარაგებულ მაღაზიაში." }, feature3: { title: "დამტკიცებული ROI", desc: "ჩვენი პარტნიორები ხედავენ დაბრუნებების 38%-ით შემცირებას." }, demoTitle: "ნახე ზუსტად რას ხედავენ შენი მომხმარებლები.", demoSubtitle: "ეს არის ვიჯეტი, რომელსაც შენი მყიდველები ხედავენ. სცადე თავად.", demoPoints: ["მუშაობს ნებისმიერ ვებსაიტზე", "მხარს უჭერს 10+ ტანსაცმლის სახეობას", "ხელმისაწვდომია კაცისა და ქალის ზომებში", "დაფუძნებულია რეალური ზომის ცხრილის მონაცემებზე"], launchDemo: "გაუშვი ცოცხალი დემო", findMyFit: "ჩემი ზომის პოვნა", formTitle: "მოითხოვე API ინტეგრაცია", formSubtitle: "მოგვიყევი შენი მაღაზიის შესახებ და ჩვენ დაგიკავშირდებით.", name: "შენი სახელი", email: "სამუშაო ელ-ფოსტა", company: "კომპანია / ბრენდის სახელი", message: "მოგვიყევი შენი მაღაზიის შესახებ", messagePlaceholder: "თვიური შეკვეთები, პლატფორმა (Shopify, WooCommerce), გამოწვევები...", submit: "ინტეგრაციის მოთხოვნის გაგზავნა", success: "მოთხოვნა მიღებულია!", successMsg: "დაგიკავშირდებით 1 სამუშაო დღის განმავლობაში." },
    pricing: { badge: "ფასები", title: "მარტივი, გამჭვირვალე ფასები", subtitle: "დაიწყე დაბრუნებების შემცირება დღეს. გამართვის საფასური არ არის.", monthly: "/ თვეში", starter: { name: "სტარტერი", price: "$299", desc: "მზარდი ბრენდებისთვის", features: ["1,000 ანალიზი/თვეში", "ძირითადი ანალიტიკა", "ელ-ფოსტის მხარდაჭერა", "სტანდარტული ზომის ცხრილები", "ვიჯეტის პერსონალიზაცია"] }, growth: { name: "ზრდა", price: "$799", desc: "დამკვიდრებული ბრენდებისთვის", features: ["10,000 ანალიზი/თვეში", "გაფართოებული ანალიტიკა", "პრიორიტეტული მხარდაჭერა", "კუსტომური ზომის ცხრილები", "ვიჯეტის პერსონალიზაცია", "API წვდომა"] }, enterprise: { name: "ენტერპრაიზი", price: "კუსტომური", desc: "მსხვილი რეტეილერებისთვის", features: ["შეუზღუდავი ანალიზები", "პირადი ანგარიშის მენეჯერი", "კუსტომური ინტეგრაციები", "SLA გარანტია", "White-label ვარიანტი"] }, getStarted: "დაიწყე", contactUs: "დაგვიკავშირდი" },
    waitlist: { badge: "ადრეული წვდომა", title: "შეუერთდი მოდის მომავალს.", subtitle: "ადრეული წვდომა შეზღუდულია. დაიკავე ადგილი სიაში.", name: "სრული სახელი", email: "ელ-ფოსტის მისამართი", join: "შეუერთდი სიას", joining: "ვუერთდებით...", success: "შენ სიაში ხარ.", successMsg: "შეგატყობინებთ, როდესაც წვდომა მზად იქნება." },
    footer: { tagline: "ხელოვნური ინტელექტით მართული ზომების სისტემა სამოსის ბრენდებისთვის. შეამცირე დაბრუნებები, გაზარდე შემოსავალი.", product: "პროდუქტი", company: "კომპანია", sizeFinder: "ზომის პოვნა", howItWorks: "როგორ მუშაობს", roadmap: "გეგმა", pricing: "ფასები", forBrands: "ბრენდებისთვის", earlyAccess: "ადრეული წვდომა", contact: "კონტაქტი", privacy: "კონფიდენციალურობის პოლიტიკა", copyright: "Clozes. ყველა უფლება დაცულია." },
  },
} as const;
