export type Lang = "en" | "ka";

export const translations = {
  en: {
    nav: { demo: "Demo", whyClozes: "Why Clozes", howItWorks: "How It Works", forBrands: "For Brands", pricing: "Pricing", joinEarlyAccess: "Join Early Access" },
    hero: { badge: "Now Onboarding Brand Partners", title1: "Experience Clothes", title2: "Before You", title3: "Wear Them.", subtitle: "AI-powered fit intelligence that predicts comfort, sizing, and outfit compatibility before your customers buy — reducing returns and increasing trust.", tryDemo: "Try the Demo", joinEarlyAccess: "Join Early Access", fewerReturns: "Fewer Returns", fitAccuracy: "Fit Accuracy", analysisTime: "Analysis Time" },
    problem: { badge: "The Problem", title: "The Hidden Cost of Poor Fit", stat1: { value: "70%", label: "of fashion returns", sub: "due to poor fit" }, stat2: { value: "$218B", label: "lost annually", sub: "in return costs" }, stat3: { value: "64%", label: "abandon purchase", sub: "due to sizing uncertainty" }, card1: { title: "Inconsistent Sizing", desc: "A medium from one brand is a large in another. Size charts are static and vary wildly across brands.", stat: "60%", statLabel: "of shoppers buy multiple sizes to return one" }, card2: { title: "The Return Crisis", desc: "Fit and sizing issues are the single biggest driver of online fashion returns, costing brands billions.", stat: "70%", statLabel: "of fashion returns are due to poor fit" }, card3: { title: "Lost Revenue", desc: "Returns don't just cost money to process — they destroy customer trust and reduce repeat purchases.", stat: "21%", statLabel: "lost globally to fashion returns annually" }, card4: { title: "Hesitation Before Buying", desc: "Uncertainty about fit is the number one reason shoppers abandon carts.", stat: "64%", statLabel: "abandon purchase due to sizing uncertainty" }},
    howItWorks: { badge: "How It Works", title1: "Intelligence", title2: "In Motion.", subtitle: "Three simple steps from measurement to confident purchase.", step1: { title: "Input Measurements", desc: "Enter your body measurements or select your garment type. Our system builds a precise fit profile tailored to your dimensions." }, step2: { title: "Neural Analysis", desc: "The Clozes Engine maps the garment's technical specs against your unique body geometry, analyzing fit across dozens of data points." }, step3: { title: "Confident Purchase", desc: "Receive your recommended size with a detailed breakdown of comfort, mobility, and fit — before you spend a penny." } },
    outfit: { badge: "Outfit Intelligence", title1: "We Go Beyond Fit.", title2: "We Build Better Outfits", subtitle: "Clozes does not just find your size — it curates complete looks that work together." },
    b2b: { badge: "Clozes Platform", title: "Power Your Store With Fit Intelligence", subtitle: "One line of code. Instant size recommendations. Fewer returns.", feature1: { title: "Drop-in SDK", desc: "Add a Find My Fit button to your product pages in less than 10 lines of code. Fully white-labeled." }, feature2: { title: "Universal Profiles", desc: "When a shopper visits any Clozes-powered store, their fit profile travels with them. Zero friction." }, feature3: { title: "Proven ROI", desc: "Our partners see an average 38% decrease in size-related returns within the first quarter." }, demoTitle: "See exactly what your customers experience.", demoSubtitle: "This is the widget your shoppers see when they click Find My Fit on your product pages. Try it yourself.", demoPoints: ["Works on any website or platform", "Supports 10+ garment types", "Available in Mens and Womens sizing", "Powered by real size chart data"], launchDemo: "Launch Live Demo", findMyFit: "Find My Fit", formTitle: "Request API Integration", formSubtitle: "Tell us about your store and we will reach out to get you set up.", name: "Your Name", email: "Work Email", company: "Company / Brand Name", message: "Tell us about your store", messagePlaceholder: "Monthly orders, platform (Shopify, WooCommerce, custom), main challenges with returns...", submit: "Submit Integration Request", success: "Request Received!", successMsg: "We will be in touch within 1 business day to discuss your integration." },
    pricing: { badge: "Pricing", title: "Simple, Transparent Pricing", subtitle: "Start reducing returns today. No setup fees, no contracts.", monthly: "/ month", starter: { name: "Starter", price: "$299", desc: "Perfect for growing brands", features: ["Up to 1,000 fit analyses/month", "Basic analytics dashboard", "Email support", "Standard size charts", "Widget customization"] }, growth: { name: "Growth", price: "$799", desc: "For established brands", features: ["Up to 10,000 fit analyses/month", "Advanced analytics & trends", "Priority support", "Custom size charts", "Widget customization", "API access"] }, enterprise: { name: "Enterprise", price: "Custom", desc: "For large retailers", features: ["Unlimited fit analyses", "Dedicated account manager", "Custom integrations", "SLA guarantee", "White-label option"] }, getStarted: "Get Started", contactUs: "Contact Us" },
    waitlist: { badge: "Early Access", title: "Join the Future of Fashion.", subtitle: "Early access is limited. Secure your spot on the waitlist.", name: "Full Name", email: "Email Address", join: "Join Waitlist", joining: "Joining...", success: "You are on the list.", successMsg: "We will notify you when your access is ready." },
    footer: { tagline: "AI-powered fit intelligence for clothing brands. Reduce returns, increase confidence, grow revenue.", product: "Product", company: "Company", sizeFinder: "Size Finder", howItWorks: "How It Works", roadmap: "Roadmap", pricing: "Pricing", forBrands: "For Brands", earlyAccess: "Early Access", contact: "Contact", privacy: "Privacy Policy", copyright: "Clozes. All rights reserved." },
  },
  ka: {
    nav: { demo: "დემო", whyClozes: "რატომ Clozes", howItWorks: "როგორ მუშაობს", forBrands: "ბრენდებისთვის", pricing: "ფასები", joinEarlyAccess: "მიიღე ადრეული წვდომა" },
    hero: { badge: "ახალი ბრენდ პარტნიორების რეგისტრაცია უკვე დაიწყო", title1: "შეაფასე ტანსაცმელი", title2: "სანამ", title3: "ჩაიცვამ.", subtitle: "ხელოვნურ ინტელექტზე დაფუძნებული სისტემა, რომელიც მომხმარებელთა მიერ პროდუქციის შეძენამდე წინასწარ პროგნოზირებს კომფორტს, ზომის შესაბამისობას და სტილის თავსებადობას — ამცირებს დაბრუნებებს და ზრდის მომხმარებლის ნდობას.", tryDemo: "სცადე დემო", joinEarlyAccess: "მიიღე ადრეული წვდომა", fewerReturns: "ნაკლები დაბრუნება", fitAccuracy: "ზომის სიზუსტე", analysisTime: "ანალიზის დრო" },
    problem: { badge: "პრობლემა", title: "არასწორი ზომის ფარული ფასი", stat1: { value: "70%", label: "ტანსაცმლის დაბრუნებების", sub: "არასწორი ზომის გამო" }, stat2: { value: "$218 მლრდ", label: "იკარგება ყოველწლიურად", sub: "დაბრუნებების ხარჯებში" }, stat3: { value: "64%", label: "უარს ამბობს შეძენაზე", sub: "ზომის არჩევის გაურკვევლობის გამო" }, card1: { title: "არათანმიმდევრული ზომები", desc: "ერთი ბრენდის M სხვა ბრენდის L-ია. ზომის ცხრილები სტატიკურია და ბრენდებს შორის ძლიერ განსხვავდება.", stat: "60%", statLabel: "მყიდველი ყიდულობს რამდენიმე ზომას რომ ერთი დაიბრუნოს" },   card2: { title: "დაბრუნების კრიზისი", desc: "ზომის პრობლემები ონლაინ მოდის დაბრუნებების მთავარი მიზეზია, ბრენდებს მილიარდებს უჯდება.", stat: "70%", statLabel: "მოდის დაბრუნება ცუდი ზომის გამო" },   card3: { title: "დაკარგული შემოსავალი", desc: "დაბრუნება მხოლოდ ფულს არ ჯდება — ის ანადგურებს მომხმარებლის ნდობას.", stat: "21%", statLabel: "იკარგება გლობალურად მოდის დაბრუნებებით" },   card4: { title: "ყიდვამდე ყოყმანი", desc: "ზომის გაურკვევლობა მთავარი მიზეზია, რის გამოც მყიდველები კალათას ტოვებენ.", stat: "64%", statLabel: "წყვეტენ შეძენას ზომის გაურკვევლობის გამო" }}, 
    howItWorks: { badge: "როგორ მუშაობს", title1: "ინტელექტი", title2: "მოქმედებაში.", subtitle: "სამი მარტივი ნაბიჯი ზომის შერჩევიდან თავდაჯერებულად შეძენამდე.", step1: { title: "შეიყვანე მონაცემები", desc: "მიუთითე სხეულის პარამეტრები ან აირჩიე ტანსაცმლის ტიპი. მიუთითე სხეულის ზომები ან აირჩიე ტანსაცმლის ტიპი. ჩვენი სისტემა ქმნის ზუსტ ინდივიდუალურ პროფილს შენი მონაცემების საშუალებით." }, step2: { title: "AI ანალიზი", desc: "Clozes-ის ძრავა ადარებს ტანსაცმლის ტექნიკურ მახასიათებლებს შენი სხეულის მონაცემებს და აფასებს შესაბამისობას მრავალ პარამეტრზე." }, step3: { title: "შეიძინე თავდაჯერებულად", desc: "მიიღე შენთვის რეკომენდებული ზომა ყიდვამდე - კომფორტის, თავისუფლად მოძრაობისა და მორგების დეტალური შეფასებით." } },
    outfit: { badge: "OutFit Intelligence", title1: "ჩვენ გთავაზობთ ზომაზე მეტს.", title2: "ჩვენ ვქმნით სრულყოფილ კომბინაციებს", subtitle: "Clozes არა მხოლოდ პოულობს შენს ზომას — ის გირჩევს როგორ შეუხამო ტანსაცმელი ერთმანეთს." },
    b2b: { badge: "Clozes პლატფორმა", title: "მიეცი შენს მაღაზიას მორგების ინტელექტი", subtitle: "მარტივი ინტეგრაცია. მყისიერი რეკომენდაციები. ნაკლები დაბრუნება.", feature1: { title: "მარტივი ინტეგრაცია", desc: "დაამატე ღილაკი “იპოვე ჩემი ზომა” პროდუქტის გვერდზე რამდენიმე წუთში. სრულიად მორგებული შენს ბრენდზე." }, feature2: { title: "უნივერსალური პროფილები", desc: "თუ მომხმარებელი ერთ Clozes-ის პარტნიორ მაღაზიაში შექმნის პროფილს, ის ავტომატურად იმუშავებს სხვა პარტნიორ მაღაზიებში." }, feature3: { title: "დადასტურებული შედეგები", desc: "ჩვენი პარტნიორი ბრენდები პირველივე კვარტალში საშუალოდ 38%-ით ამცირებენ ზომასთან დაკავშირებულ დაბრუნებებს." }, demoTitle: "ნახე ზუსტად რას ხედავენ შენი მომხმარებლები.", demoSubtitle: "ეს არის ვიჯეტი, რომელსაც მომხმარებელი ხედავს ღილაკზე “იპოვე ჩემი ზომა” დაჭერის შემდეგ. სცადე თავადაც.", demoPoints: ["მუშაობს ნებისმიერ ვებსაიტსა და პლატფორმაზე", "მხარს უჭერს 10-ზე მეტ ტანსაცმლის კატეგორიას", "ხელმისაწვდომია ქალისა და მამაკაცის ზომებისთვის", "დაფუძნებულია რეალური ზომების მონაცემებზე"], launchDemo: "გაუშვი დემო ვერსია", findMyFit: "იპოვე ჩემი ზომა", formTitle: "API ინტეგრაციის მოთხოვნა", formSubtitle: "მოგვწერე შენი მაღაზიის შესახებ და დაგიკავშირდებით ინტეგრაციის დასაწყებად.", name: "სახელი და გვარი", email: "სამუშაო ელ-ფოსტა", company: "კომპანიის / ბრენდის სახელი", message: "მოგვიყევი შენი მაღაზიის შესახებ", messagePlaceholder: "თვიური შეკვეთების რაოდენობა, პლატფორმა (Shopify, WooCommerce ან სხვა), დაბრუნებასთან დაკავშირებული ძირითადი გამოწვევები...", submit: "მოთხოვნის გაგზავნა", success: "მოთხოვნა მიღებულია!", successMsg: "ინტეგრაციის დეტალების განსახილველად დაგიკავშირდებით 1 სამუშაო დღის განმავლობაში." },
    pricing: { badge: "ფასები", title: "მარტივი, გამჭვირვალე ფასები", subtitle: "დაიწყე დაბრუნებების შემცირება დღესვე. დამატებითი გადასახადებისა და კონტრაქტების გარეშე.", monthly: "/ თვეში", starter: { name: "საწყისი", price: "$299", desc: "იდეალურია მზარდი ბრენდებისთვის", features: ["1,000-მდე ანალიზი/თვეში", "საბაზისო ანალიტიკა", "ელ-ფოსტის მხარდაჭერა", "სტანდარტული ზომის ცხრილები", "ვიჯეტის პერსონალიზაცია"] }, growth: { name: "ზრდა", price: "$799", desc: "განვითარებული ბრენდებისთვის", features: ["10,000-მდე ანალიზი/თვეში", "გაფართოებული ანალიტიკა და ტენდენციები", "პრიორიტეტული მხარდაჭერა", "ინდივიდუალური ზომის ცხრილები", "ვიჯეტის პერსონალიზაცია", "API წვდომა"] }, enterprise: { name: "კორპორატიული", price: "ინდივიდუალური", desc: "მსხვილი ბრენდებისა და ონლაინ მაღაზიებისთვის", features: ["ულიმიტო ანალიზები", "პერსონალური ანგარიშის მენეჯერი", "ინდივიდუალური ინტეგრაციები", "SLA გარანტია", "White-label ვარიანტი"] }, getStarted: "დაწყება", contactUs: "დაგვიკავშირდი" },
    waitlist: { badge: "ადრეული წვდომა", title: "გახდი მოდის მომავლის ნაწილი.", subtitle: "ადრეული წვდომის ადგილები შეზღუდულია. დაიკავე ადგილი მომლოდინეთა სიაში.", name: "სახელი და გვარი", email: "ელ-ფოსტის მისამართი", join: "მომლოდინეთა სიაში დამატება", joining: "იგზავნება...", success: "თქვენ სიაში ხართ.", successMsg: "წვდომის გააქტიურებისთანავე შეგატყობინებთ." },
    footer: { tagline: "AI-ზე დაფუძნებული ზომისა და მორგების ინტელექტი ტანსაცმლის ბრენდებისთვის. შეამცირე დაბრუნებები, გაზარდე ნდობა და შემოსავალი.", product: "პროდუქტი", company: "კომპანია", sizeFinder: "ზომის პოვნა", howItWorks: "როგორ მუშაობს", roadmap: "გზამკვლევი", pricing: "ფასები", forBrands: "ბრენდებისთვის", earlyAccess: "ადრეული წვდომა", contact: "კონტაქტი", privacy: "კონფიდენციალურობის პოლიტიკა", copyright: "Clozes. ყველა უფლება დაცულია." },
  },
} ;
